import { Routes } from "@angular/router";

export const routes: Routes = [
  { path: "accordion", loadComponent: () => import("./pages/accordion/accordion.component").then(c => c.AccordionComponent), data: { title: "accordion" } },
  { path: "alert", loadComponent: () => import("./pages/alert/alert.component").then(c => c.AlertComponent), data: { title: "alert" } },
  { path: "countdown", loadComponent: () => import("./pages/countdown/countdown.component").then(c => c.CountdownComponent), data: { title: "countdown" } },
  { path: "cover", loadComponent: () => import("./pages/cover/cover.component").then(c => c.CoverComponent), data: { title: "cover" } },
  { path: "drop", loadComponent: () => import("./pages/drop/drop.component").then(c => c.DropComponent), data: { title: "drop" } },
  { path: "dropdown", loadComponent: () => import("./pages/dropdown/dropdown.component").then(c => c.DropdownComponent), data: { title: "dropdown" } },
  { path: "dropnav", loadComponent: () => import("./pages/dropnav/dropnav.component").then(c => c.DropnavComponent), data: { title: "dropnav" } },
  { path: "filter", loadComponent: () => import("./pages/filter/filter.component").then(c => c.FilterComponent), data: { title: "filter" } },
  { path: "form-custom", loadComponent: () => import("./pages/form-custom/form-custom.component").then(c => c.FormCustomComponent), data: { title: "form-custom" } },
  { path: "grid", loadComponent: () => import("./pages/grid/grid.component").then(c => c.GridComponent), data: { title: "grid" } },
  { path: "height-match", loadComponent: () => import("./pages/height-match/height-match.component").then(c => c.HeightMatchComponent), data: { title: "height-match" } },
  { path: "height-placeholder", loadComponent: () => import("./pages/height-placeholder/height-placeholder.component").then(c => c.HeightPlaceholderComponent), data: { title: "height-placeholder" } },
  { path: "height-viewport", loadComponent: () => import("./pages/height-viewport/height-viewport.component").then(c => c.HeightViewportComponent), data: { title: "height-viewport" } },
  { path: "icon", loadComponent: () => import("./pages/icon/icon.component").then(c => c.IconComponent), data: { title: "icon" } },
  { path: "image", loadComponent: () => import("./pages/image/image.component").then(c => c.ImageComponent), data: { title: "image" } },
  { path: "inverse", loadComponent: () => import("./pages/inverse/inverse.component").then(c => c.InverseComponent), data: { title: "inverse" } },
  { path: "leader", loadComponent: () => import("./pages/leader/leader.component").then(c => c.LeaderComponent), data: { title: "leader" } },
  { path: "modal", loadComponent: () => import("./pages/modal/modal.component").then(c => c.ModalComponent), data: { title: "modal" } },
  { path: "nav", loadComponent: () => import("./pages/nav/nav.component").then(c => c.NavComponent), data: { title: "nav" } },
  { path: "navbar", loadComponent: () => import("./pages/navbar/navbar.component").then(c => c.NavbarComponent), data: { title: "navbar" } },
  { path: "notification", loadComponent: () => import("./pages/notification/notification.component").then(c => c.NotificationComponent), data: { title: "notification" } },
  { path: "off-canvas", loadComponent: () => import("./pages/off-canvas/off-canvas.component").then(c => c.OffCanvasComponent), data: { title: "off-canvas" } },
  { path: "parallax", loadComponent: () => import("./pages/parallax/parallax.component").then(c => c.ParallaxComponent), data: { title: "parallax" } },
  { path: "scroll", loadComponent: () => import("./pages/scroll/scroll.component").then(c => c.ScrollComponent), data: { title: "scroll" } },
  { path: "scrollspy", loadComponent: () => import("./pages/scrollspy/scrollspy.component").then(c => c.ScrollspyComponent), data: { title: "scrollspy" } },
  { path: "slider", loadComponent: () => import("./pages/slider/slider.component").then(c => c.SliderComponent), data: { title: "slider" } },
  { path: "slideshow", loadComponent: () => import("./pages/slideshow/slideshow.component").then(c => c.SlideshowComponent), data: { title: "slideshow" } },
  { path: "sortable", loadComponent: () => import("./pages/sortable/sortable.component").then(c => c.SortableComponent), data: { title: "sortable" } },
  { path: "sticky", loadComponent: () => import("./pages/sticky/sticky.component").then(c => c.StickyComponent), data: { title: "sticky" } },
  { path: "svg", loadComponent: () => import("./pages/svg/svg.component").then(c => c.SvgComponent), data: { title: "svg" } },
  { path: "switcher", loadComponent: () => import("./pages/switcher/switcher.component").then(c => c.SwitcherComponent), data: { title: "switcher" } },
  { path: "toggle", loadComponent: () => import("./pages/toggle/toggle.component").then(c => c.ToggleComponent), data: { title: "toggle" } },
  { path: "tooltip", loadComponent: () => import("./pages/tooltip/tooltip.component").then(c => c.TooltipComponent), data: { title: "tooltip" } },
  { path: "upload", loadComponent: () => import("./pages/upload/upload.component").then(c => c.UploadComponent), data: { title: "upload" } },
  { path: "video", loadComponent: () => import("./pages/video/video.component").then(c => c.VideoComponent), data: { title: "video" } },
];
